gems: ['bourbon', 'neat', 'jekyll-assets']

# Structure configuration
source: ./source
destination: ./build

assets:
  cache: .asset-cache
  digest: true

# Site settings
title: "Inqury @ UC Santa Cruz"
description: UC Santa Cruz Research Magazine
permalink: /:year/:title/

# Name of project on Github
# baseurl: /inquiry.ucsc.edu

exclude: ['.asset-cache']

# lunr_search:
#   js: 'js'
#   excludes: [feed.xml]

collections:
  articles:
    output: true
    permalink: /:path/

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false

email: "a-mail@mail.mail"
logo: "inquiry.svg"
cover: "2016/cover-photo.jpg"
name: "Inquiry @ UCSC"
author: "Inquiry @ UCSC"
author_image: "/assets/images/author.jpg"

issue: "2015"